set nocompatible
source $VIMRUNTIME/vimrc_example.vim
"source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

" Tab&space setup
set tabstop=4
set expandtab

" Fonts
set guifont=Inconsolata:h14

" Colorscheme setup
if has('gui_running')
    "set background=light
    set background=dark
else
    set background=dark
endif
colorscheme solarized

" 窗口最大化
"autocmd GUIEnter * simalt ~x

" Show commands
set showcmd

" Turn off gvim error bells
set noeb
set vb t_vb=

" Easy key for scroll up and down
" scroll up
nmap <BS> <C-Y>
nmap <TAB> <C-Y>
" scroll down
nmap <SPACE> <C-E>

" Macro Hotkeys
nmap <F1> @w
nmap <F2> @q

" File buffer change
nmap <F3> :bp<CR>
nmap <F4> :bn<CR>
nmap <F5> gd
nmap <F6> <C-o>

" Fold setting
set foldmethod=indent
set shiftwidth=4
set foldlevel=100

" Indent
set autoindent
set smartindent
filetype plugin indent on

" Backup dir
set bdir=D:/program/vimbackupdir

" Auto change line for Chinese chariters
set textwidth=1000
